INSERT INTO member(memberid, password, membername) VALUES('aa11','aa','AA11');
INSERT INTO member(memberid, password, membername) VALUES('bb11','bb','AA11');
INSERT INTO member(memberid, password, membername) VALUES('cc11','cc','AA11');

INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W1', 'T1', 'C1');
INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W2', 'T2', 'C2');
INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W3', 'T3', 'C3');
INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W4', 'T4', 'C4');
INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W5', 'T5', 'C5');
INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W6', 'T6', 'C6');
INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W7', 'T7', 'C7');
INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W8', 'T8', 'C8');
INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W9', 'T9', 'C9');
INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W10', 'T10', 'C10');
INSERT INTO BOARD(WRITER,TITLE,CONTENT) VALUES('W11', 'T11', 'C11');
